/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-accent': 'var(--bg-accent)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-hover': 'var(--bg-hover)',
        card: 'var(--card)',
        'card-fg': 'var(--card-fg)',
        chrome: 'var(--chrome)',
        text: 'var(--text)',
        'text-strong': 'var(--text-strong)',
        muted: 'var(--muted)',
        'muted-strong': 'var(--muted-strong)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        accent: 'var(--accent)',
        'accent-fg': 'var(--accent-fg)',
        'accent-hover': 'var(--accent-hover)',
        'accent-subtle': 'var(--accent-subtle)',
        'accent-glow': 'var(--accent-glow)',
        ring: 'var(--ring)',
        ok: 'var(--ok)',
        'ok-fg': 'var(--ok-fg)',
        'ok-subtle': 'var(--ok-subtle)',
        warn: 'var(--warn)',
        'warn-subtle': 'var(--warn-subtle)',
        danger: 'var(--danger)',
        'danger-fg': 'var(--danger-fg)',
        'danger-subtle': 'var(--danger-subtle)',
        info: 'var(--info)',
        aim: 'var(--aim)',
        'aim-subtle': 'var(--aim-subtle)',
        clarify: 'var(--clarify)',
        'clarify-subtle': 'var(--clarify-subtle)',
        'diff-add': 'var(--diff-add)',
        'diff-add-text': 'var(--diff-add-text)',
        'diff-del': 'var(--diff-del)',
        'diff-del-text': 'var(--diff-del-text)',
        'diff-hunk': 'var(--diff-hunk)',
        'diff-hunk-text': 'var(--diff-hunk-text)',
        'diff-meta-text': 'var(--diff-meta-text)',
      },
      fontFamily: {
        body: ['var(--font-body)'],
        mono: ['var(--mono)'],
      },
      fontSize: {
        // Semantic scale — 4 tiers, each with a paired line-height so small text
        // never inherits the body's 1.55 leading. Add new keys here instead of
        // writing another `text-[Npx]` one-off. See docs/design-craft-rules.md.
        '2xs': ['11px', { lineHeight: '16px' }],
        meta: ['12px', { lineHeight: '18px' }],
        'body-s': ['13px', { lineHeight: '20px' }],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-xl)',
        inner: 'var(--shadow-inset)',
      },
      keyframes: {
        rise: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'slide-in-left': { from: { opacity: '0', transform: 'translateX(-16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        blink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        'dot-breathe': { '0%,100%': { opacity: '.6', transform: 'scale(.9)' }, '50%': { opacity: '1', transform: 'scale(1.1)' } },
        'brand-glow': { '0%': { opacity: '.6', transform: 'scale(1)' }, '100%': { opacity: '1', transform: 'scale(1.05)' } },
        'gradient-shift': { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
      },
      animation: {
        rise: 'rise .35s cubic-bezier(.16,1,.3,1) backwards',
        'fade-in': 'fade-in .2s ease',
        'slide-up': 'slide-up .3s cubic-bezier(.16,1,.3,1) backwards',
        'slide-in-right': 'slide-in-right .3s cubic-bezier(.16,1,.3,1) backwards',
        'slide-in-left': 'slide-in-left .25s cubic-bezier(.16,1,.3,1) backwards',
        'scale-in': 'scale-in .2s cubic-bezier(.16,1,.3,1) backwards',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        blink: 'blink .6s step-end infinite',
        'dot-breathe': 'dot-breathe 2s ease-in-out infinite',
        'brand-glow': 'brand-glow 5s ease-in-out infinite alternate',
        'gradient-shift': 'gradient-shift 20s ease infinite',
      },
    },
  },
  plugins: [],
}
